apiVersion: v1
type: kubernetes.io/basic-auth
kind: Secret
data:
  username: juby
  # This may change, but isn't intended to be used for
  # anything other than the initial setup
  password: {{ randAscii 32 | b64enc | quote }}
metadata:
  name: juby-secret
  labels:
    app.kubernetes.io/name: vitagraphs
    app.kubernetes.io/part-of: vitagraphs
