apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  labels:
    app: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "{{ .Values.storage.storageClassName }}"
  resources:
    requests:
      storage: "{{ .Values.storage.configSize }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  labels:
    app: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "{{ .Values.storage.storageClassName }}"
  resources:
    requests:
      storage: "{{ .Values.storage.mediaSize }}"
