apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config-template
data:
  openclaw.json.tmpl: |
    {
      "gateway": {
        "bind": "lan",
        "mode": "remote",
        "controlUi": {
          "dangerouslyAllowHostHeaderOriginFallback": true
        },
        "auth": {
          "mode": "token"
        }
      },
      "channels": {
        "telegram": {
          "botToken": "${TELEGRAM_BOT_TOKEN}",
          "dmPolicy": "allowlist",
          "allowFrom": [${TELEGRAM_ALLOW_FROM}]
        }
      },
      "models": {
        "providers": {
          "gemini": {
            "apiKey": "${GOOGLE_API_KEY}"
          }
        }
      }
    }
